EngineHub/CommandHelper

- src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitPlayerEvents.java
- src/main/java/com/laytonsmith/abstraction/events/MCPlayerLoginEvent.java
- src/main/java/com/laytonsmith/core/events/drivers/PlayerEvents.java
It's not possible to get the player's UUID in this event -- with pinfo(player(), 20) for example. However, it's very useful to have.
> Added UUID to player_login event

- src/main/resources/syntax-templates/notepad++/default.xml
- src/main/resources/syntax-templates/notepad++/obsidian.xml
- src/main/resources/syntax-templates/notepad++/solarized_dark.xml
- src/main/resources/syntax-templates/notepad++/solarized_light.xml
I made double quoted strings highlight like single quoted strings, and then gave a nested exception to @ keyword and @{} delimiter. It's not perfect, but this is the closest I could get it. It highlights vars in smart strings in almost all cases, except for @ when not a prefix -- eg. "word@var". However, "word@{var}word" and "word @var word" work as expected.
> Add smart string support in notepad++ syntax highlighters.

- src/main/resources/syntax-templates/sublime/default.xml
Ticks could close quoted strings and quotes could close ticked strings. Also newlines where the string is closed with nothing else were not accounted for.
> Fixed ticks and quote syntax highlighting

- src/main/java/com/laytonsmith/core/Script.java
I discovered this simple little bottleneck when testing scripts with WarmRoast. 
When running the below test script, it consistently ran for 44-45 seconds before the optimization, and ran consistently for 33-34 seconds after the optimization. So over several runs it ran about 34% faster for this particular test, but given the location of the optimization we should see similar results for many scripts.
```
*:/test = >>>
@start = time();
for(@x = 0, @x < 300, @x++) {
for(@y = 1, @y < 100, @y++) {
for(@z = 0, @z < 300, @z++) {
get_block_at(@x, @y, @z, 'world');
}
}
}
@stop = time();
msg((@stop - @start).'ms');
<<<
```
> Faster matching for procedures

- src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitPlayerEvents.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitVehicleEvents.java
- src/main/java/com/laytonsmith/abstraction/events/MCPlayerMoveEvent.java
- src/main/java/com/laytonsmith/abstraction/events/MCPlayerTeleportEvent.java
- src/main/java/com/laytonsmith/abstraction/events/MCVehicleMoveEvent.java
- src/main/java/com/laytonsmith/core/events/drivers/PlayerEvents.java
- src/main/java/com/laytonsmith/core/events/drivers/VehicleEvents.java
- Fixed first bind's threshold being cleared.
- Added threshold into fake event so that we don't have to measure twice, and so lower threshold binds don't also execute.
- Get current location once per player.
- Removed unused Bukkit implementations to avoid confusion.
> Fixed player|vehicle move threshold prefilters.

- src/main/java/com/laytonsmith/core/functions/Environment.java
When specifying an index, it's ~32% faster when iterating over a 50x50x50 cube. This is helpful for scripts that iterate over a lot of blocks, but only need one type of block info.
> Added optional argument to get_block_info()

- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCCommand.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCObjective.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitBlockEvents.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitVehicleEvents.java
- src/main/java/com/laytonsmith/abstraction/events/MCVehicleEvent.java
- src/main/java/com/laytonsmith/core/functions/Commands.java
- src/main/java/com/laytonsmith/core/functions/PlayerManagement.java
- src/main/java/com/laytonsmith/core/functions/Scoreboards.java
CMDHELPER-2686 fixed
CMDHELPER-2877 fixed
CMDHELPER-2916 addressed
CMDHELPER-2929 addressed
CMDHELPER-3046 fixed
Also fixes unhelpful stacktraces being thrown from CREs in registered commands. These have been replaced with normal CH error reports with accurate script info.
> Fix various stacktraces, crashes, incompletenesses.

- src/main/java/com/laytonsmith/core/functions/World.java
get_yaw returned its pfacing value * -1 and get_pitch rotated the wrong way around.
> get_yaw and get_pitch now match pfacing.

- src/main/java/com/laytonsmith/core/functions/InventoryManagement.java
ptake_item(@player, null, @amount) returned an error in core
(NullPointerException in the match() method). It will now throw a
ConfigRuntimeException with type IllegalArgumentException instead.
> Fixed error in core caused by ptake_item.

- src/main/resources/syntax-templates/atom/default.cson
There's a typo in the Atom syntax template - fixed here.  :tada:
> Fix Atom syntax template

- src/main/java/com/laytonsmith/core/constructs/CArray.java
- src/main/java/com/laytonsmith/core/functions/ArrayHandling.java
- src/test/java/com/laytonsmith/core/functions/ArrayHandlingTest.java
- src/test/java/com/laytonsmith/core/functions/StringHandlingTest.java
- array_get(@array) or @array[] only cloned 2 arrays deep. It will now recursively clone the whole array.
- Added array_deep_clone(@array).
- Added array_shallow_clone(@array).
> Fixed array_get's deep cloning.

- src/main/java/com/laytonsmith/abstraction/enums/MCGameRule.java
There's a few missing game rules in the `MCGameRule` enum (notably `DOENTITYDROPS`) - this adds them!  :+1: 
See also: http://minecraft.gamepedia.com/Commands#gamerule
> Add missing game rules to MCGameRule enum

- src/main/java/com/laytonsmith/core/functions/PlayerManagement.java
When pinf() was used without arguments in a non-player environment (in
main.ms for example), it would cause a NullPointerException (error in
core). The exception will now be handled within the pinfo exec.
> Fixed error in core caused by pinfo.

- src/main/java/com/laytonsmith/core/functions/Minecraft.java
This is a partial implementation of http://youtrack.sk89q.com/issue/CMDHELPER-2641
TPS still isn't there, and it looks like it takes a loop to measure it (Essentials implementation here: https://github.com/essentials/Essentials/blob/a2c43d822c66e617a84df9a8f074b9c3a3e32fae/Essentials/src/com/earth2me/essentials/EssentialsTimer.java).  Not sure if we want to do that or not.
> Add uptime and gc stats to get_server_info

- src/main/java/com/laytonsmith/core/functions/ArrayHandling.java
- src/main/java/com/laytonsmith/core/functions/BasicLogic.java
- Fixed 18 errors in core (wrong amount of arguments passed).
- Removed unused imports.
> Fixed 18 errors in core in BasicLogic.java.

- src/main/java/com/laytonsmith/core/Static.java
- src/main/java/com/laytonsmith/core/functions/PlayerManagement.java
After jb-aero added UUID support to Static.GetPlayer(), it no longer handled null before checking the string length. This was the real source of the problem for the pinfo() fix. This may also fix other related cases.
> Handle null in Static.GetPlayer() again; Also fixes failed test.

- src/main/java/com/laytonsmith/abstraction/bukkit/events/drivers/BukkitBlockListener.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/drivers/BukkitEntityListener.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/drivers/BukkitInventoryListener.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/drivers/BukkitPlayerListener.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/drivers/BukkitServerListener.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/drivers/BukkitVehicleListener.java
- src/main/java/com/laytonsmith/commandhelper/CommandHelperMessageListener.java
This reduces an unbound event's operation time by about 80-90%. On my server TriggerExternal() currently adds over 0.1ms to each event.
To make the transition smoother, this commit avoids removing the functionality from events that are used by known extensions. That means player/server commands, inventory open/close, and projectile hit events still use TriggerExternal(). Some can be updated to just use TriggerListener, but as of this moment command events need TriggerExternal() to allow extensions to cancel aliases. (like with SKCompat)
> Remove deprecated EventUtils.TriggerExternal() from most events to reduce overhead

- src/main/java/com/laytonsmith/abstraction/MCLivingEntity.java
- src/main/java/com/laytonsmith/abstraction/bukkit/entities/BukkitMCLivingEntity.java
- src/main/java/com/laytonsmith/core/ObjectGenerator.java
- src/main/java/com/laytonsmith/core/functions/EntityManagement.java
- src/main/java/com/laytonsmith/core/functions/PlayerManagement.java
This allows an optional sixth parameter to `set_mob_effect()` and `set_peffect()` to configure whether particles are visible at all.  The `particles` value is also returned from `get_peffects()` and `get_mob_effects()` as a boolean.
Since I'm not 100% sure on backwards compatibility of the parameter inside Bukkit, the 5-parameter constructor for `PotionEffect` is only used if specifically requested.
Documentation has been added for all changes.
> Allow disabling of potion particles

- src/main/java/com/laytonsmith/abstraction/blocks/MCBlock.java
- src/main/java/com/laytonsmith/abstraction/bukkit/blocks/BukkitMCBlock.java
- src/main/java/com/laytonsmith/core/functions/Environment.java
- get_block_power(locationArray) returns the redstone power supplied to
that block.
- is_block_powered(locationArray, [powerMode]) now has a powerMode
argument which can be used to select direct power, indirect power or
both (default to both, this was the previous behaviour).
> Added get_block_power and expanded is_block_powered.

- src/main/java/com/laytonsmith/abstraction/MCPlayer.java
- src/main/java/com/laytonsmith/abstraction/bukkit/entities/BukkitMCPlayer.java
- src/main/java/com/laytonsmith/core/functions/PlayerManagement.java
TotalExperience in Minecraft is total accumulated experience, rather than current total experience. This was confusing and unhelpful to scripters so we previously changed this to return the experience necessary to get the current level + xp bar. I use a Bukkit method now to get exp for next level, but still required a method to get total exp for current level.
One debatable change: TotalExperience was previously updated to the value given in set_ptexp(), but it doesn't make sense to lower total accumulated experience. It also meant we were setting two things when ptexp() was only getting one thing. So instead I preserve the experience score.
> Update ptexp() and set_ptexp() for 1.8

- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
- src/main/java/com/laytonsmith/core/compiler/keywords/LiteralKeyword.java
- src/main/java/com/laytonsmith/core/constructs/CDouble.java
- src/main/java/com/laytonsmith/core/functions/InventoryManagement.java
- src/test/java/com/laytonsmith/core/OptimizationTest.java
- src/test/java/com/laytonsmith/testing/ArrayTest.java
Allows both 'null' and null indexes in set_pinv()
> Fixes literal keywords and decimals in labels (CMDHELPER-2990)

- src/main/java/com/laytonsmith/core/functions/EventBinding.java
Create a new IVariable to put in the new IVariableList. I believe this is correct, and I tested several scenarios.
> Fixed custom parameters in bind() being overwritten (CMDHELPER-2664)

- src/main/java/com/laytonsmith/core/functions/EventBinding.java
This is an improved overwrite fix to the one in build 2927. This is how custom parameters functioned prior to my previous fix when using the assign() workaround. 
With this:
```
@a = array(1, 2, 3);
foreach(@b in @a) {
// bind
}
```
I tested these custom parameters:
```
@b = @b // the old workaround
@a = 1 // this breaks the array reference outside the bind, just like prior to 2927
@b
@a
@c = @a[0];
```
I also incremented @a[0] inside the bind and outside the bind to verify the reference, in cases where it shouldn't have been passed and where it should have.
> Pass bind() custom parameters by reference, not value

- src/main/java/com/laytonsmith/core/functions/DataHandling.java
assign(datatype, notAnIvar, value) throwed a stacktrace because it
attempted to cast the notAnIvar to IVariable. This also happend when
using for example this code (as it gets optimized to assign()):
array NotAnIvar = value;
> Fixes CMDHELPER-3066 (error in core, ClassCastEx)

- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
- src/main/java/com/laytonsmith/core/functions/StringHandling.java
- src/test/java/com/laytonsmith/core/OptimizationTest.java
- src/test/java/com/laytonsmith/core/functions/StringHandlingTest.java
- Made -@b stay -@b instead of the string "-@b" (as - @b behaves). Also
works with $vars.
- Made notAVariable -@var compile as neg(@var). Also works with $vars.
- Fixes CMDHELPER-3104 and CMDHELPER-3102.
- Removed unused imports.
> Made -@b and - @b the same and made @a=-@b work.

- src/main/java/com/laytonsmith/core/ObjectGenerator.java
When rotating 360 deg to the right (multiple times), the ploc()[yaw]
values are correct. When you rotate more left than right after you've
joined, the ploc()[yaw] values were negative. This fix makes the yaw
always be positive, as it should be.
> yaw in ploc was incorrect (negative) when rotating more left than right in total rotation since join.

- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
- src/test/java/com/laytonsmith/core/OptimizationTest.java
Negations happend to a value after a MINUS sign, if the object in front of the MINUS sign was no variable, ivariable or atomic literal. This made @a[0] - @b and such negate @b instead of performing a subtraction.
Fixes CMDHELPER-3105
> Bugfix in the neg code in the compiler.

- src/main/java/com/laytonsmith/abstraction/MCPlayer.java
- src/main/java/com/laytonsmith/abstraction/bukkit/entities/BukkitMCPlayer.java
- src/main/java/com/laytonsmith/core/functions/PlayerManagement.java
Decided to go with set_pspectator_target(), unless someone objects. I think pspectate_entity() was the second most popular choice, but I think the two functions would be less complimentary in that case. Last chance to change it.
> Add spectator target functions

- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
- src/test/java/com/laytonsmith/testing/StaticTest.java
- Functions with OptimizationOption.CONSTANT_OFFLINE would have their
exec() method called before checking if the right number of arguments
was passed to it. This caused errors in core and no compile errors on
code such as "abs(1,2,3,4,5,6)" while abs() should only take one
argument.
- Small cleanup (forgotten in last PR, no functional changes).
> Respect numArgs in specific optimization.

- src/main/java/com/laytonsmith/core/ObjectGenerator.java
- src/main/java/com/laytonsmith/core/Static.java
- src/main/java/com/laytonsmith/core/constructs/CArray.java
- src/main/java/com/laytonsmith/core/events/BoundEvent.java
- src/main/java/com/laytonsmith/core/events/drivers/BlockEvents.java
- src/main/java/com/laytonsmith/core/events/drivers/PlayerEvents.java
- src/main/java/com/laytonsmith/core/functions/ArrayHandling.java
- src/main/java/com/laytonsmith/core/functions/BukkitMetadata.java
- src/main/java/com/laytonsmith/core/functions/Cmdline.java
- src/main/java/com/laytonsmith/core/functions/EntityManagement.java
- src/main/java/com/laytonsmith/core/functions/Environment.java
- src/main/java/com/laytonsmith/core/functions/ExtensionMeta.java
- src/main/java/com/laytonsmith/core/functions/Minecraft.java
- src/main/java/com/laytonsmith/core/functions/Persistence.java
- src/main/java/com/laytonsmith/core/functions/SQL.java
- src/main/java/com/laytonsmith/core/functions/Scoreboards.java
- src/main/java/com/laytonsmith/core/functions/Web.java
- src/main/java/com/laytonsmith/core/functions/World.java
So after the previous PR, I changed and used the GetAssociativeArray() methods and removed the now unused forceAssocativeMode() method. I also fixed the array assignment in the constructor so that it appropriately sets the initial capacity if given items, and removed some impossible conditions in the compare() method.
For those who didn't see the previous PR, the primary goal is to avoid the extra cost of switching from a normal array to an associative array, since to do so it creates and throws an exception. Every event was throwing 1-3 exceptions by default, and this was adding up in some profiling I did.
> Optimizations

- src/main/java/com/laytonsmith/core/constructs/CArray.java
Many extensions were not compatible with CH anymore. This commit adds a
final deprecated push that gives extension developers some time to
update their extensions.
> Re-added the old (now deprecated) CArray.push syntax.

- src/main/java/com/laytonsmith/core/functions/StringHandling.java
to_lower used to stringify the argument passed to it. This change will
give a user an appropriate exception when passing anything else to the
function. If a player would like to stringify the argument anyways, he
could do that using the string() function.
> Added type check to to_lower and to_upper.

- src/main/java/com/laytonsmith/abstraction/AbstractConvertor.java
Tasks created with set_timeout() are not being removed.
I'm not sure if this is where/how you want to do this, so feel free to do your own fix. Since the tracker is down, I thought I'd offer this PR instead.
> Fix leak for non-repeating tasks

- src/main/java/com/laytonsmith/core/functions/InventoryManagement.java
When the player argument was supplied, it would also use it as the slot
number. This has been fixed.
> BugFix in set_pheld_slot

- src/main/java/com/laytonsmith/core/functions/Environment.java
- set_block_at() threw an error in core when a block ID such as
'0:random' was given, this has been fixed.
- set_block_at() used stringsbuilders to parse the block ID. This has
been changed to something more fancy.
> Fixed an error in core in set_block_at.

- src/main/java/com/laytonsmith/core/functions/DataHandling.java
- src/test/java/com/laytonsmith/core/functions/DataHandlingTest.java
Due to the removed deprecated export(@var) and import(@var), IVariables were not resolved before calling the exec. This caused the need to use export(string(@var), @value) and import(string(@var)). With this commit, it will accept IVariables and return an exception if the IVariable does not contain a CString.
> Made import/export accept an IVar as key.

- src/main/java/com/laytonsmith/core/functions/DataHandling.java
- When trying to assign something to a non-IVariable with 2 arguments,
it would throw a ClassCastException when the first argument is no
IVariable. This is because the type check was in the wrong place.
- Removed double checks, double assignments and useless code.
> Fixed CCE in assign.

- src/main/java/com/laytonsmith/PureUtilities/TermColors.java
\033[0m resets the ANSI color to normal. The default bukkit output color
is not always normal, so \033[m should be used instead. This is also
what Bukkit uses.
> Changed the ANSI reset code used in console().

- src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitMiscEvents.java
- src/main/java/com/laytonsmith/abstraction/events/MCCommandTabCompleteEvent.java
- src/main/java/com/laytonsmith/core/events/drivers/ServerEvents.java
If you return null in onTabComplete, Bukkit will default to online player name tab completion. (players the sender can see) It also defaults to players if a tab completer isn't set, but we need to set a tab completer so that our event fires for all registered commands.
> Tab complete online player names by default for registered commands

- src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitPlayerEvents.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitVehicleEvents.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/drivers/BukkitPlayerListener.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/drivers/BukkitVehicleListener.java
- src/main/java/com/laytonsmith/core/events/AbstractEvent.java
- src/main/java/com/laytonsmith/core/events/Event.java
- src/main/java/com/laytonsmith/core/events/EventUtils.java
- src/main/java/com/laytonsmith/core/events/drivers/PlayerEvents.java
- src/main/java/com/laytonsmith/core/events/drivers/VehicleEvents.java
This is a major internal change to how player_move and vehicle_move events are fired. The old method uses threading to reduce overhead, but it had low accuracy and was prone to ConcurrentModificationExceptions. (in some cases causing data corruption, though this could be significantly improved) This uses actual server events to avoid threading problems, but maintains most of the benefit of thresholds. But since thresholds are calculated on the main thread, it does increase overhead. And since it isn't throttled to 500ms, it can fire more frequently at a threshold of 1. (200-250ms when walking) That part is probably not that bad, because before it would fire all player_move events every 500ms, which could cause micro-stutter. Also, now if you cancel, it cancels the actual event, creating …
> Rewrite player_move and vehicle_move to use server events. Add world prefilters.

- src/main/java/com/laytonsmith/core/ObjectGenerator.java
max_stack_size(@array) changed the @array if data was missing. It now
clones the array before making a modification.
> Made max_stack_size not modify the given array.

- pom.xml
- src/main/java/com/laytonsmith/PureUtilities/ClassLoading/ClassDiscovery.java
- src/main/java/com/laytonsmith/PureUtilities/ClassLoading/ClassMirror/ClassMirror.java
- src/main/java/com/laytonsmith/PureUtilities/ClassLoading/ClassMirror/ClassMirrorVisitor.java
Fixes compatibility with PaperSpigot and TacoSpigot.
You were using a very old version of ASM, which can't read java 8 jars.
Since PaperSpigot updated to 1.8, you need to update ASM in order to support them.
Unlike #339 I can confirm that metadata-caching works.
All unit-tests pass, but I don't have scripts to test with.
> Cleanup classfile reading and upgrade to latest ASM

- src/main/java/com/laytonsmith/core/constructs/CClosure.java
- src/main/java/com/laytonsmith/core/exceptions/CRE/AbstractCREException.java
For reference, the relevant part of the core error is this:
```
java.lang.ClassCastException: java.lang.IndexOutOfBoundsException cannot be cast to com.laytonsmith.core.exceptions.CRE.CRECausedByWrapper
at com.laytonsmith.core.exceptions.CRE.AbstractCREException.getCausedBy(AbstractCREException.java:139)
at com.laytonsmith.core.exceptions.CRE.AbstractCREException.getExceptionObject(AbstractCREException.java:105)
at com.laytonsmith.core.functions.Exceptions$complex_try.execs(Exceptions.java:444)
```
> Exception fixes

- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitConvertor.java
Queue, thread unsafe and x_run_on_main_thread_... function calls caused
an Exception to be thrown by the Bukkit scheduler when the server was
shutting down. This PR hopefully fixes that.
> Don't schedule tasks when the plugin is disabled.

- src/main/java/com/laytonsmith/core/functions/PlayerManagement.java
- src/main/java/com/laytonsmith/core/functions/World.java
We currently have to teleport twice (with set_ploc and pfacing) to change location and yaw/pitch, even though location arrays contain yaw/pitch. set_ploc() is almost entirely rewritten here because it was dated and hard to work with. I also fixed the docs and tested several combinations of inputs.
spawn_falling_block() just wasn't using the new vector generator, so I fixed that.
> Improve set_ploc and spawn_falling_block

- src/main/java/com/laytonsmith/core/events/drivers/PlayerEvents.java
modify_event in player_chat would throw Exceptions that were displayed
in console as:
- FormatException: Conversion = '"'
- FormatException: d !=
org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer
- Errors in core
This commit checks if the new format is valid for how MineCraft
interpretes it and gives a better Exception message.
> Check format before modifying the player_chat event.

- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCWorld.java
- src/main/java/com/laytonsmith/abstraction/bukkit/entities/BukkitMCPlayer.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitEntityEvents.java
- src/main/java/com/laytonsmith/abstraction/enums/MCSound.java
- src/main/java/com/laytonsmith/abstraction/enums/bukkit/BukkitMCSound.java
- src/main/java/com/laytonsmith/commandhelper/CommandHelperPlugin.java
- src/main/java/com/laytonsmith/core/functions/Environment.java
This uses the same dynamic ENUM system as BiomeType and EntityType to build a map of old sound names to the same sounds in the new ENUM. This maintains backwards compatibility with scripts and MC versions.
This does not add the new sounds. It's going to be tricky to decide on the names for that and I just need to get this out.
In the future we could decide to ditch the old ENUM in favor of the new one, then just convert the new ENUM to the old via the same mechanism if MCVersion is less than 1.9. Of course, this would soft-break existing scripts. (currently scripts don't fail, but the sounds don't play)
> Map existing Sound ENUM to new Sound ENUM

- pom.xml
- src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitPlayerEvents.java
- src/main/java/com/laytonsmith/core/events/drivers/PlayerEvents.java
Since the getHand() method in PlayerInteractEvent does not exist in
Bukkit versions prior to 1.9, it became incompatible with those version
after this was added to CH. This fixes that.
> Added backwards compatibility to player_interact.

- src/main/java/com/laytonsmith/core/functions/ArrayHandling.java
array_implode(string, array) would throw an error in core because it
checked for ArrayAccess instrad of CArray. CStrings implement
ArrayAccess but throw an UnsupportedOperationException on the keySet()
method. This has been fixed by changing the ArrayAccess check to a
CArray check.
> Fixed an error in core in array_implode.

- src/main/java/com/laytonsmith/PureUtilities/TermColors.java
- src/main/java/com/laytonsmith/core/Static.java
- Removed seperate resets between all ANSI color/style changes (ESC[m).
- Added resets to arguments in ANSI color (but not style) changes.
- Added normal brightness argument to ANSI color changes for non-bright
colors.
- Enabled ANSI style codes on Windows (this is consistent with the
output the broadcast() function gives and useful if you were to parse
the codes yourself in a custom console).
- console(colorize('&4test &ntest')) and broadcast(colorize('&4test
&ntest')) now output the same ANSI codes in console.
> Fixed ANSI colorcode output from console().

- src/main/java/com/laytonsmith/core/functions/BasicLogic.java
- src/test/java/com/laytonsmith/core/functions/BasicLogicTest.java
switch() with a dynamic array as default return value would give an
compile error about cases having to be static. This was caused by
optimization code handling the default code as case code.
Example of what used to give an error:
switch('bla', array(array()))
switch('bla', 'case1', 'return1', array(array('Default case return in 2
arrays')))
> Allow dynamic array return in default switch case.

- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitConvertor.java
When the MC server shuts down and CommandHelper is disabled, scheduling
a task will result in a CancellationException. This Exception is now
caught and ignored or logged based on whether CommandHelper was still
enabled or not (before this commit, it was a raw stacktrace on the
console from a Timer thread).
> Catch CancellationExceptions when shutting down.

- src/main/java/com/laytonsmith/abstraction/MCFireworkBuilder.java
- src/main/java/com/laytonsmith/abstraction/MCFireworkEffect.java
- src/main/java/com/laytonsmith/abstraction/MCFireworkEffectMeta.java
- src/main/java/com/laytonsmith/abstraction/MCFireworkMeta.java
- src/main/java/com/laytonsmith/abstraction/MCWorld.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitConvertor.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCFireworkBuilder.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCFireworkEffect.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCFireworkEffectMeta.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCFireworkMeta.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCWorld.java
- src/main/java/com/laytonsmith/core/ObjectGenerator.java
- src/main/java/com/laytonsmith/core/functions/ItemMeta.java
- src/main/java/com/laytonsmith/core/functions/Minecraft.java
This updates the firework meta so that it supports multiple effects per firework, and also adds meta for the firework charge. I made a best attempt at maintaining compatibility with old scripts. Old item array formats for setting a firework or launching a firework will continue to work! However, scripts that read or modify a firework meta array returned from a function may be unavoidably affected. I also tied in launch_firework() into the object generator for consistency and made sure some special formatting was still supported. 
Scripts can still do this, for example:
```
bind(player_interact, null, associative_array('item': 401, 'hand': 'main_hand'), @event) {
cancel();
launch_firework(@event['location'], pinv(player(), null)['meta']['firework']);
}
```
Or even this now with the …
> Update Firework meta

- src/main/java/com/laytonsmith/abstraction/MCLivingEntity.java
- src/main/java/com/laytonsmith/abstraction/MCTeam.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCTeam.java
- src/main/java/com/laytonsmith/abstraction/bukkit/entities/BukkitMCEntity.java
- src/main/java/com/laytonsmith/abstraction/bukkit/entities/BukkitMCLivingEntity.java
- src/main/java/com/laytonsmith/abstraction/enums/MCOption.java
- src/main/java/com/laytonsmith/abstraction/enums/MCOptionStatus.java
- src/main/java/com/laytonsmith/abstraction/enums/bukkit/BukkitMCOption.java
- src/main/java/com/laytonsmith/abstraction/enums/bukkit/BukkitMCOptionStatus.java
- src/main/java/com/laytonsmith/core/functions/EntityManagement.java
- src/main/java/com/laytonsmith/core/functions/Scoreboards.java
The NameTagVisibility *should* also use this new Option system that the new team options use, although I have no idea how to make it backwards compatible right now, so I left it out of the change for now
> Added 'collisionrule' and 'deathmessagevisibility' options for teams & entity ai functions

- src/main/java/com/laytonsmith/abstraction/enums/EnumConvertor.java
The current ENUM converter checker takes an enormous amount of space per warning. This is mostly redundant information and is quite spammy on non-latest Spigot versions. I significantly reduced it by almost 200 characters, and it starts the message with the relevant ENUM type. If you still feel we need some messages about what causes this and if it can cause problems, I think that needs to be added before or after the checks.
> Reduce noise in mostly harmless ENUM mismatch warnings

- src/main/java/com/laytonsmith/abstraction/enums/bukkit/BukkitMCEntityType.java
PRing this just to make sure I'm not missing something here. (@jb-aero) 
UNKNOWN entity types are sometimes handled as more specific classes than just MCEntity. For example, currently when EchoPet causes a CreatureSpawnEvent the entity type is UNKNOWN. CH wraps it as an MCEntity and causes an exception when BukkitMCCreatureSpawnEvent tries to cast it to MCLivingEntity. By setting the wrapperclass as null, it forces BukkitConvertor.BukkitGetCorrectEntity() to find the most specific entity class.
> Force BukkitGetCorrectEntity to determine a more specific entity class for UNKNOWN entity type

- src/main/java/com/laytonsmith/core/functions/PlayerManagement.java
The 16 character list name limit has been removed from Bukkit. The exact
limit is unknown and depends on the client packet receive code, but it's
at least 30.000.
> Removed 16 char limit from set_list_name().

- src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitBlockEvents.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/drivers/BukkitBlockListener.java
- src/main/java/com/laytonsmith/abstraction/events/MCBlockBreakEvent.java
- src/main/java/com/laytonsmith/core/events/drivers/BlockEvents.java
There is no official way to modify drops from a BlockBreakEvent, so instead CH sets the block to air and spawns items. Previously protection plugins would have no say on whether CH could break a block when this was done. Also block loggers would see the block is AIR and ignore the event or record it inaccurately. This creates a new event so that other plugins can log or cancel the action accurately. It also lets lower priority binds see the modified drops.
This also fixes experience not dropping when item drops were modified.
It seemed to do well in testing. WorldGuard would cancel the break if the player didn't have permission, and everything worked as expected. It does use 2 events, but almost all plugins ignore cancelled breaks. There are some things in Spigot that I would think would …
> Improve block_break when drops are modified

- src/main/java/com/laytonsmith/database/MySQLProfile.java
- src/main/resources/docs/SQL
An optional additional argument to enable/disable ssl.
Not adding the <useSSL> Tag, will default to not sending the argument.
<useSSL /> will default to false, any mix of true/TRUE will be interpreted as true.
> Added useSSL to MySQLProfile

- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
When compiling "function(['bla'])" or similar code, the compiler would
attempt to convert the ['bla'] to "array_get(...)". Because the actual
array to get it from does not exist, it looks for this at index "-1",
causing an uncaught ArrayOutOfBoundsException. This commit adds a check
for this case and gives an expected compile exception instead.
> Fixed ArrayOutOfBoundsEx in the compiler.

- src/main/java/com/laytonsmith/core/functions/DataHandling.java
> Typo in foreach examples()

- src/main/java/com/laytonsmith/abstraction/bukkit/entities/BukkitMCCommandMinecart.java
- src/main/java/com/laytonsmith/abstraction/entities/MCCommandMinecart.java
- src/main/java/com/laytonsmith/commandhelper/CommandHelperPlugin.java
- src/main/java/com/laytonsmith/commandhelper/CommandHelperServerListener.java
- src/main/java/com/laytonsmith/core/AliasCore.java
- src/main/java/com/laytonsmith/core/environments/CommandHelperEnvironment.java
- src/main/java/com/laytonsmith/core/functions/EntityManagement.java
- src/main/java/com/laytonsmith/core/functions/Meta.java
- src/main/java/com/laytonsmith/core/functions/PlayerManagement.java
- src/main/java/com/laytonsmith/core/functions/Weather.java
Since CraftBukkit 1.12.1, execution of a CommandBlock fires a
ServerCommandEvent, allowing CommandHelper to listen to 'direct' aliases
(without /runalias prefix) in command blocks. This commit causes command
blocks without "/runalias" to be handled the same as the ones with
"/runalias" (effectively adding a "#" in front of the command block name
so player() will never return a valid player name for command blocks).
This commit also adds support for minecart command blocks in all places
where command block blocks are already supported.
> Command block support and bugfixes.

- pom.xml
- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
- src/main/java/com/laytonsmith/core/Script.java
- src/main/java/com/laytonsmith/core/Static.java
- src/main/java/com/laytonsmith/core/functions/Meta.java
- src/test/java/com/laytonsmith/core/functions/MetaTest.java
Script labels are now processed only once, instead of every time a function is executed. This also isolates script labels so that they're not modified after they're set, which is what the environment is for. These changes should not alter current behavior.
I don't expect any issues, but I want to do more testing before this is pulled. However, I want your impression on this approach and if you have any suggestions. I don't want to do the testing if you don't like it, and I had trouble communicating what I wanted to do here before.
So the git diff on the scriptas() function turned out pretty shitty. What I did there was removed script.setLabel() usages (as we probably shouldn't ever change the script label) and added the same script.enforceLabelPermissions() call that's at the beginning of …
> Optimize alias permission labels

- src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitBlockEvents.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/drivers/BukkitBlockListener.java
- src/main/java/com/laytonsmith/abstraction/events/MCBlockFadeEvent.java
- src/main/java/com/laytonsmith/core/events/Driver.java
- src/main/java/com/laytonsmith/core/events/drivers/BlockEvents.java
> Add block_fade event

- src/main/java/com/laytonsmith/abstraction/bukkit/entities/BukkitMCPlayer.java
- src/main/java/com/laytonsmith/commandhelper/CommandHelperPlugin.java
- src/main/java/com/laytonsmith/core/AliasCore.java
- src/main/java/com/laytonsmith/core/packetjumper/PacketJumper.java
Despite only being used for sudo() right now, ClassDiscovery for the server jar adds up to 10 seconds to the startup time. The Bukkit convertor init also synchronizes during the ClassDiscovery process which may make things worse. This commit proposes that this extra time is not a necessary sacrifice and implements an alternative reflection method where needed.
> Change Minecraft reflection method to improve startup times

- src/main/java/com/laytonsmith/core/constructs/Construct.java
Both the GetConstruct and GetPOJO methods contained loops over
Lists/Maps with a getter of a value from those Lists/Maps in them,
effectively being O(n^2) runtime complexity (with an exception of Hash
implementations, where a lookup is O(1) instead of O(n)).
In this commit, those loops have been changed to loops over the entryset
(for Maps) or changed to using an iterator (Lists). The new runtime
complexity for both is O(n).
> Improved runtime complexity GetConstruct/GetPOJO

- pom.xml
Repository "mvn2.sk89q.com" has been replaced with "maven.sk89q.com" long ago. The mvn2 repository is currently offline and might never come back, the replacing repository is online and recommended over the deprecated one (source: wizjany).
> Updated sk89q repo in pom.

- src/main/java/com/laytonsmith/core/Script.java
- src/test/java/com/laytonsmith/core/MethodScriptCompilerTest.java
Many commands were not detected as ambigous properly. Examples:
- *:/cmd2 $arg AND *:/cmd2 $arg
- *:/cmd11 $arg $arg2 AND *:/cmd11 $arg $arg2 [$arg3]
- *:/cmd14 arg AND *:/cmd14 $arg
- *:/cmd15 arg AND *:/cmd15 [$arg]
This commit will cause ambigous commands to throw a compile exception as
expected.
The previous code caught an IndexOutOfBoundsException, which's
fillInStacktrace() costed ~35% runtime spent in
AliasCore.LocalPackage.consoleMSA(). This has been replaced with a size
check to reduce runtime for MSA compiles by roughly this 35% (as tested
with my scripts and setup on my server with 254 defined aliases).
> BugFix for ambigous command detection.

- src/main/java/com/laytonsmith/abstraction/MCBeaconInventory.java
- src/main/java/com/laytonsmith/abstraction/MCBrewerInventory.java
- src/main/java/com/laytonsmith/abstraction/MCFurnaceInventory.java
- src/main/java/com/laytonsmith/abstraction/blocks/MCBeacon.java
- src/main/java/com/laytonsmith/abstraction/blocks/MCBrewingStand.java
- src/main/java/com/laytonsmith/abstraction/blocks/MCChest.java
- src/main/java/com/laytonsmith/abstraction/blocks/MCDispenser.java
- src/main/java/com/laytonsmith/abstraction/blocks/MCDropper.java
- src/main/java/com/laytonsmith/abstraction/blocks/MCFurnace.java
- src/main/java/com/laytonsmith/abstraction/blocks/MCHopper.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitConvertor.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCBeaconInventory.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCBrewerInventory.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCFurnaceInventory.java
- src/main/java/com/laytonsmith/abstraction/bukkit/blocks/BukkitMCBeacon.java
- src/main/java/com/laytonsmith/abstraction/bukkit/blocks/BukkitMCBrewingStand.java
- src/main/java/com/laytonsmith/abstraction/bukkit/blocks/BukkitMCChest.java
- src/main/java/com/laytonsmith/abstraction/bukkit/blocks/BukkitMCDispenser.java
- src/main/java/com/laytonsmith/abstraction/bukkit/blocks/BukkitMCDropper.java
- src/main/java/com/laytonsmith/abstraction/bukkit/blocks/BukkitMCFurnace.java
- src/main/java/com/laytonsmith/abstraction/bukkit/blocks/BukkitMCHopper.java
- src/main/java/com/laytonsmith/abstraction/bukkit/blocks/BukkitMCShulkerBox.java
- src/main/java/com/laytonsmith/core/ObjectGenerator.java
Furnaces will now have a "burntime", "cooktime" and "inventory" metadata tag. "inventory" is an array with 3 possible keys: "result", "fuel" and "smelting".
This PR prevents set_pinv(pinv()) to erase furnace metadata and adds the ability to get/modify it.
> Added blockstate data support for furnaces.

- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
- src/test/java/com/laytonsmith/core/MethodScriptCompilerTest.java
Bug examples:
array(5)[0] - 3 would become 2, but array(5)[0] -3 would become string '5 -3'.
2 - 3, 2-3 and 2- 3 would become -1, but 2 -3 and 2     -3 would become string '2 -3'.
This commit fixes the minus sign interpretation by the lexer, ignoring whitespaces in front of the '-' sign and with an additional case to support array_get's in format "@a[0]-value".
> Fixed invalid minus sign interpretation.

- checkstyle.xml
- checkstyle_suppressions.xml
- pom.xml
- Allow star imports in "...Test.java" classes.
- Move checkstyle execution from "validate" to "test" phase (allow compile to happen before checking syntax and don't run checkstyle when not running tests).
> Checkstyle update

- src/main/java/com/laytonsmith/core/events/drivers/PlayerEvents.java
The function "set_metadata" and similar require an entity to be online. 
The entity (player) is known by the event already, but not the rest of the server. 
Injecting it, to make it accessible.
> JoinEvent inject Entity

- src/main/java/com/laytonsmith/annotations/api.java
- src/main/java/com/laytonsmith/core/functions/CompositeFunction.java
- src/test/java/com/laytonsmith/testing/RandomTests.java
- Optimize `testFunctionsAreOnlyDefinedOnce` test to run in O(n) instead of O(n^2) where n = 743 (and n^2 = 552049). Locally, this reduces the test time of te RandomTests class (being 12±2 seconds on my system) by roughly 3 or 4 seconds on my system.
- Fixed javadoc comment.
- Fixed case where not setting up the global environment makes the `testFunctionsAreOnlyDefinedOnce` test fail when executed on itself in an IDE.
> RandomTest optimization

- src/main/java/com/laytonsmith/core/functions/Meta.java
- src/main/java/com/laytonsmith/core/functions/StringHandling.java
Disable secure_string and get_locales boilerplate test because these slow down the build time by Travis CI significantly. secure_string's boilerplate test can easily take 6 minutes and even cause Travis CI to time out (>10 minutes combined).
> Disable secure_string and get_locales boilerplate test

- .gitignore
- checkstyle.xml
- pom.xml
- src/main/java/com/laytonsmith/abstraction/MCServer.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCServer.java
- src/main/java/com/laytonsmith/core/functions/Echoes.java
- Make broadcast(message, players) fire an event through its Bukkit implementation so that it matches the broadcast(message) and broadcast(message, permission) behaviour.
- Extend broadcast() documentation to include all behaviour.
> Fix broadcast() function event consistency

- src/main/java/com/laytonsmith/abstraction/Convertor.java
- src/main/java/com/laytonsmith/abstraction/MCDoubleChest.java
- src/main/java/com/laytonsmith/abstraction/MCServer.java
- src/main/java/com/laytonsmith/abstraction/MCVirtualInventoryHolder.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitConvertor.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCDoubleChest.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCInventory.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCServer.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCVirtualInventoryHolder.java
- src/main/java/com/laytonsmith/abstraction/bukkit/entities/BukkitMCVillager.java
- src/main/java/com/laytonsmith/abstraction/entities/MCVillager.java
- src/main/java/com/laytonsmith/abstraction/enums/MCInventoryType.java
- src/main/java/com/laytonsmith/core/Static.java
- src/main/java/com/laytonsmith/core/events/drivers/InventoryEvents.java
- src/main/java/com/laytonsmith/core/functions/InventoryManagement.java
- src/main/java/com/laytonsmith/tools/Interpreter.java
- src/test/java/com/laytonsmith/testing/StaticTest.java
New functions: popen_inventory(), pviewing(), get_inventory_viewers(), get_virtual_inventories(), create_virtual_inventory(), and delete_virtual_inventory().
New "virtual" prefilter for inventory_click, inventory_drag, inventory_open, and inventory_close events.
New inventory "holder" data for inventory_open and inventory_close events.
So this is my attempt to bring virtual inventories to CommandHelper proper instead of having to rely on CHVirtualChests (and without breaking the extension). This allows us to use the same inventory functions and events for virtual inventories as we do for in-world inventories held by entities and blocks. I also used this opportunity to add some other useful functions: popen_inventory(), pviewing() and get_inventory_viewers(). This addresses a few tickets …
> Add new inventory functions and virtual inventories.

- src/main/java/com/laytonsmith/PureUtilities/ZipReader.java
- src/main/java/com/laytonsmith/core/exceptions/ConfigRuntimeException.java
- src/main/java/com/laytonsmith/tools/Interpreter.java
- src/main/java/org/bstats/bukkit/Metrics.java
Before this PR, the return value of the closure passed to set_uncaught_exception_handler would result in:
- true -> Suppress exception.
- null -> Use default uncaught exception handler.
- false -> Use default uncaught exception handler and print the java stacktrace to the cause.
- exception in closure -> Use default uncaught exception handler for the exception in the closure and suppress the first exception.
The behaviour set by this commit is:
- true -> Suppress exception.
- null -> Use default uncaught exception handler.
- false -> Use default uncaught exception handler.
- exception in closure -> Use default uncaught exception handler to print both exceptions.
This new behaviour matches the documentation of set_uncaught_exception_handler.
> Fix set_uncaught_exception_handler closure return behaviour

- src/main/java/com/laytonsmith/core/functions/Minecraft.java
The hardness and blastResistance traits are unavailable for non-block materials (such as REDSTONE), causing material_info('REDSTONE') to throw an error in core. This commit no longer returns these traits for non-block materials and throws a CREIllegalArgumentException when these traits are specifically asked for on non-block materials.
> Handle block-specific trait exceptions in material_info

- src/main/java/com/laytonsmith/core/AliasCore.java
CommandHelper reads auto_include.ms to UTF-8 but others not. (Maybe use OS default encoding)
That makes problem when using non english characters for example "한글".
In addition, `StreamUtils.GetSystemOut().println("Non english character")` prints broken character.
I reproduced that problems in my default OS encoding(x-windows-949)
> Fix non include file encoding to UTF-8

- src/main/java/com/laytonsmith/core/functions/DataHandling.java
- Fix + extend proc() docs (proc name is not optional).
- Fix closure docs (they take variables, not variable names).
- Use `params` for proc and closure parameters. This is what they actually are and this is consistent with bind(), which calls them custom_params.
> Update Datahandling docs

- src/main/java/com/laytonsmith/core/constructs/CFunction.java
- src/main/java/com/laytonsmith/core/objects/Element.java
- src/main/java/com/laytonsmith/core/objects/ElementDefinition.java
- src/main/java/com/laytonsmith/core/objects/ObjectDefinition.java
The PureUtilities CheckOverrides causes the build to fail when @override annotations are missing.
> Fix build failure

- src/main/resources/docs/Operators
Since there is no obvious way to view rendered docs locally, the rendering of these changes has not been tested.
> Fix operator order documentation and add operator associativity

- src/main/java/com/laytonsmith/core/Procedure.java
- src/main/java/com/laytonsmith/core/functions/Compiler.java
- src/main/java/com/laytonsmith/core/functions/DataHandling.java
- src/test/java/com/laytonsmith/core/functions/DataHandlingTest.java
- src/test/java/com/laytonsmith/testing/ProcedureTest.java
The tests should make it obvious what I was going for here, but I'm not sure this is entirely consistent with your plans. void is a bit weird.
Also, there's a bit of hard-to-read code that I cleaned up in the latter part of getProcedure() too. So, if you're wondering what I changed there, it does exactly the same thing. It's just easier to understand now.
> Fix void handling for proc return types and assignment

- src/main/java/com/laytonsmith/core/functions/CompositeFunction.java
You can easily reproduce this problem using below code
```
@a = null
broadcast(string_contains(@a, 't'))
```
Then CommadHelper will print unknown source of error.
So I tried simple way to fix that. 
But I'm not sure that is this correct way. Please review this.
> Fix unknown target in CompositeFunction

- src/main/java/com/laytonsmith/core/constructs/CClassType.java
ArrayList is much faster here, since we generally want to loop through this list anyway. It also maintains the SortedSet order, if that's useful. It seems intentional to use SortedSet there, though I'm not sure why type unions need an order.
I mentioned this yesterday, but I'm not sure you caught it, since you were focused on caching. I just did some testing today and it looks good. I saw 10-19% reductions in total operation times. (~13% avg)
(BTW, I did 5 runs per build, and the runs are around 30 seconds. It loops through a compilation of various operations I've measured over the years, though I've removed IO to reduce variation. It doesn't count compilation time.)
> Avoid unnecessary hashing when getting list of types

- src/main/java/com/laytonsmith/core/Script.java
This bypasses the ExtensionManager.GetFunction() bottleneck while retaining its benefits. I actually think this might have been an oversight at some point? Either way, worth bringing up since it reduces operation time by another ~20% from the previous build.
> Use cached Function in CFunction

- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
- src/main/java/com/laytonsmith/core/Script.java
- src/main/java/com/laytonsmith/core/constructs/CFunction.java
- src/main/java/com/laytonsmith/tools/langserv/LangServ.java
- src/test/java/com/laytonsmith/core/OptimizationTest.java
- src/test/java/com/laytonsmith/core/functions/DataHandlingTest.java
- src/test/java/com/laytonsmith/testing/RandomTests.java
This is an early implementation that makes `@closure(@arg1, @arg2)` equivalent to `execute(@arg1, @arg2, @closure)`. Also fixes LangServ incorrectly checking procedures as functions.
While this is obviously not how you eventually plan to add this, this does add initial support for this concept and makes proc checking more clear. This minimal modification implementation should be just as easily updated with whatever you have planned.
This obviously doesn't support `@array['closure'](@arg1, @arg2)`, which will require more work.
> Support executing closures in variables using function syntax.

- src/main/java/com/laytonsmith/core/functions/Compiler.java
- src/test/java/com/laytonsmith/core/OptimizationTest.java
Among other bugs, addresses https://dev.enginehub.org/youtrack/issue/CMDHELPER-3174
The current implementation alternated between symbol and value, but errored when encountering multiple symbols in a row (except for a single special case of an initial "!"). This fixes almost all of that by grabbing all contiguous symbols. I also simplified the additive assignment by adding it after the right-hand-side is collected.
There are still issues with ++ and --, but I tested to make sure those issues existed in previous builds too. It works properly in more cases now as the tests demonstrate. It's probably best if we determine if they're postfix or prefix in the lexer when we still have whitespace. That's for another time.
I was concerned that this was too greedy, but my attempts to break it …
> Fix issues w/ multiple contiguous symbols in assignment (CMDHELPER-3174)

- src/main/java/com/laytonsmith/core/constructs/Construct.java
This is optimal in cases we can expect it to not be a UserObject. This results in 16-28% reduction in overall operation time in my random scripts I use for profiling, but it depends on the assumption that I understand how UserObject is used here. UserObject will still use the old methodology, thus should still work if extending a native class, I assume.
> Check only native types in Construct for isInstanceOf().

- src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitBlockEvents.java
- src/main/java/com/laytonsmith/abstraction/events/MCBlockPistonEvent.java
- src/main/java/com/laytonsmith/abstraction/events/MCBlockPistonExtendEvent.java
- src/main/java/com/laytonsmith/abstraction/events/MCBlockPistonRetractEvent.java
- src/main/java/com/laytonsmith/core/events/drivers/BlockEvents.java
Add affectedBlocks key to the piston_retract event. This is used when slime or honey blocks are pulled, pulling adjacent blocks with them.
Compatibility:
- Used Bukkit method was added in 2015.
- Deprecated `retractedLocation` key in `piston_retract` is maintained.
> Add affectedBlocks to piston_retract event

- src/main/java/com/laytonsmith/abstraction/bukkit/entities/BukkitMCEnderman.java
- src/main/java/com/laytonsmith/abstraction/entities/MCEnderman.java
- src/main/java/com/laytonsmith/core/functions/EntityManagement.java
Fix calling entity_spec on an Enderman that is not carrying a block resulting in a NullPointerException.
> Fix NPE in entity_spec for Enderman

- src/main/java/com/laytonsmith/core/functions/ObjectManagement.java
- src/main/java/com/laytonsmith/core/objects/DuplicateObjectDefinitionException.java
- src/main/java/com/laytonsmith/core/objects/ObjectDefinitionTable.java
- src/test/java/com/laytonsmith/core/objects/ObjectDefinitionTableTest.java
The DuplicateObjectDefintionException.java class is misspelled,
it should be DuplicateObjectDefinitionException.java
This commit fixes the class name.
Resolves: #1180
> fix: Fix bug #1180 misspelled class name

- src/main/java/com/laytonsmith/core/functions/BossBar.java
- src/main/java/com/laytonsmith/core/functions/BukkitMetadata.java
- src/main/java/com/laytonsmith/core/functions/Commands.java
- src/main/java/com/laytonsmith/core/functions/Echoes.java
- src/main/java/com/laytonsmith/core/functions/Enchantments.java
- src/main/java/com/laytonsmith/core/functions/EntityManagement.java
- src/main/java/com/laytonsmith/core/functions/Environment.java
- src/main/java/com/laytonsmith/core/functions/InventoryManagement.java
- src/main/java/com/laytonsmith/core/functions/Minecraft.java
- src/main/java/com/laytonsmith/core/functions/MobManagement.java
- src/main/java/com/laytonsmith/core/functions/PlayerManagement.java
- src/main/java/com/laytonsmith/core/functions/PluginMeta.java
- src/main/java/com/laytonsmith/core/functions/Recipes.java
- src/main/java/com/laytonsmith/core/functions/Scoreboards.java
- src/main/java/com/laytonsmith/core/functions/Trades.java
- src/main/java/com/laytonsmith/core/functions/World.java
Add CommandHelperEnvironment `@api` annotation arguments for Minecraft dependent functions, such that these functions can no longer be used in cmdline mode (and crash due to NoClassFoundDefErrors).
> Add missing CommandHelperEnvironments

- src/main/java/com/laytonsmith/core/functions/DataHandling.java
- src/main/java/com/laytonsmith/core/functions/FileHandling.java
- src/main/java/com/laytonsmith/core/functions/IncludeCache.java
- src/main/java/com/laytonsmith/core/functions/Sandbox.java
- Bypass Security.CheckSecurity(File) checks in cmdline mode.
- Move existing in-cmdline-mode checks before Security checks, since Security checks can throw an IOEx that shouldn't have to occur in cmdline mode.
> Fix cmdline file access security checks

- src/main/java/com/laytonsmith/core/functions/DataHandling.java
this allows for:
`executeas(null, null, @closure)`
> pass current MCCommandSender on null for executeas

- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
- src/main/java/com/laytonsmith/core/constructs/CFunction.java
Cache the required environments for each function in CFunction and use that for lookups where possible. Also don't do FunctionList lookups where the function is already cached. This makes the flow as follows:
1. postParseRewrite() caches all existing functions.
2. Other compiler steps use the cached functions, or get null when they don't exist.
3. checkFunctionsExist() does a lookup in the FunctionList if the function is not cached, and generates the compile exception if it doesn't exist.
> Use cache instead of FunctionList lookups

- src/main/java/com/laytonsmith/core/compiler/analysis/StaticAnalysis.java
- src/main/java/com/laytonsmith/core/functions/DataHandling.java
- Fix NPE in StaticAnalysis.requireIVariable() and StaticAnalysis.requireClassType() that occurs when passing in invalid syntax. Eventually, the parse has to catch these errors and halt compilation such that the AST in further steps only contains valid terms. For now, catch possible NPEs in the later stage and print invalid term classes instead such that it doesn't crash.
- Fix exception during scope graph generation for assign(var, val) with an invalid variable type.
- For default or AUTO declarations, still require the value to be instanceof Mixed to prevent things such as void assigns.
> Static Analysis patch

- src/main/java/com/laytonsmith/core/constructs/CClassType.java
- src/main/java/com/laytonsmith/tools/langserv/LangServ.java
The CClassType invalidType is cached in a thread-unsafe way. This causes problems when LangServ is performing an operation on the same CClassType, since one thread can start using the Mixed[1] created by the other thread before it is populated with data, getting null when reading its first element.
> Fix NPEs in CClassType

- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
- src/main/java/com/laytonsmith/core/compiler/CompilerEnvironment.java
- src/main/java/com/laytonsmith/core/compiler/analysis/StaticAnalysis.java
- src/main/java/com/laytonsmith/core/compiler/keywords/IfKeyword.java
- src/main/java/com/laytonsmith/core/compiler/keywords/TryKeyword.java
- src/main/java/com/laytonsmith/core/exceptions/AbstractCompileException.java
- src/main/java/com/laytonsmith/core/exceptions/ConfigCompileException.java
- src/main/java/com/laytonsmith/core/exceptions/ConfigCompileGroupException.java
- src/test/java/com/laytonsmith/core/MethodScriptCompilerTest.java
- src/test/java/com/laytonsmith/core/NewExceptionHandlingTest.java
Allow keywords to be part of other syntax than their keyword processing code is written for. An example is code `array(static: 1)`, which generates a compile error when attempting to process the keyword `static`, while it is actually part of valid `array()` syntax.
Fixes #1220 (but not yet for non-keywords such as `array(int: 1)`, which still results in `{ms.lang.int: 1}`).
> Allow keywords to be part of other syntax

- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
- src/main/java/com/laytonsmith/core/functions/Compiler.java
Pass literal `\` as literal `\\` to `__smart_string__`, so that `__smart_string__` can disambiguate between `"\@"` and `"\\@"`, rather than getting the same input for both.
As this function is an internal compiler function, and users that do use it would now have to pass double escaped `\` into the function to make it work properly, the function has also been renamed to `__smart_string__` to fit the other compiler functions.
Fixes #1229.
This is the new behavior of smart strings how users would use them, and how `__smart_string__` now receives its arguments. Note that it is not possible to fix this without either moving the `\\` escape handling to `__smart_string__` (which is what I did), or moving `\@` handling to the parser itself, removing the need for `__smart_string__`.
@LadyCailin …
> Fix '@' escaping in smart strings

- src/main/java/com/laytonsmith/core/ProfilesImpl.java
- src/main/java/com/laytonsmith/core/Static.java
Fix NPE in LangServ while generating the environment without having a profiles file in the MethodScript directory. This fix creates an empty ProfilesImpl, such that any usage of the Profiles object will simply be like if the profiles file were empty.
> Fix NPE in LangServ while generating environment

- src/main/java/com/laytonsmith/abstraction/MCWorld.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCWorld.java
- src/main/java/com/laytonsmith/core/functions/World.java
Adding `get_world_day()` and `set_world_day()` for accessing a world's day counter. Useful for changing/checking the phase of the moon.
Essentially the same as the vanilla `/time query day` and `/time set 1d`
> Add get/set functions for world day

- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
- src/main/java/com/laytonsmith/core/compiler/OptimizerObject.java
- src/main/java/com/laytonsmith/core/functions/Compiler.java
- src/main/java/com/laytonsmith/core/functions/ControlFlow.java
Parse `__autoconcat__()` to the new `__statements__()` instead of `sconcat()` in strict mode. `__statements__()` takes arguments of any type and returns `void` for typechecking, so compile errors will be generated in cases where `__autoconcat__()` used to insert `sconcat()`s, or in other words, where the user has either forgotten to put some `.` concat, or where the user has made a mistake.
This change does not affect non-strict mode, as automatically inserting concats is a feature there.
Alias syntax should also remain possible in strict mode, but only when the whole alias is nicely concatenated together by the user. Inserting multiple arguments/statements will cause the code block to be interpreted as a statements block and not as an alias redirect.
> Don't parse __autoconcat__ to sconcat in strict mode

- src/main/resources/syntax-templates/sublime3/default.sublime-syntax
'= was recognized as keyword, instead of a quote start.
Now quotes (and comments) will be checked first, before detecting keywords.
> Fix Sublime3 Syntax-Highlighting

- src/main/java/com/laytonsmith/core/functions/Scheduling.java
The example code uses 10000 milliseconds, but the output is described as waiting 5 seconds. It should say 10 seconds instead :)
> set_timeout example output should say 10 seconds

- src/main/java/com/laytonsmith/abstraction/enums/MCChatColor.java
- src/main/java/com/laytonsmith/core/Static.java
- src/main/java/com/laytonsmith/core/functions/Echoes.java
- src/test/java/com/laytonsmith/core/functions/EchoesTest.java
Adding support for any RGB colours in `color()`, using the 1.16 `§x§r§r§g§g§b§b` format. Detects any arg that starts with a # and splits it up accordingly. Won't do anything if it's invalid hex, or not long enough.
Also added support for it to `colorize()`, given an & before the #.
> Support RGB colours

- src/main/java/com/laytonsmith/core/compiler/analysis/StaticAnalysis.java
- src/main/java/com/laytonsmith/core/constructs/InstanceofUtil.java
- Move instanceof logic from SA to InstanceofUtil. The new generics check here is questionable as the actual generic geclaration from instanceofThis is never used, and some other LeftHandGenericUse is passed in instead. This could use a revision that is out of scope for this commit.
- Fix SA instanceof `(CClassType, CClassType)` method signature being redirected to the `(Mixed, CClassType)` instanceof method, effectively making all types `ClassType` instead of their actual type.
> Move instanceof logic to InstanceofUtil + Fix SA instanceof reference

- src/main/java/com/laytonsmith/core/events/drivers/EntityEvents.java
item_drop: Added 'id' to event data list as it was missing
item_spawn: Added an explanation for the 'item' event data parameter as it was missing
> Update item_* function documentation

- src/main/java/com/laytonsmith/commandhelper/CommandHelperPlugin.java
This fixes an issue where CommandHelper aliases cannot be executed via RCON. Attempting to run a command results in nothing happen, there is no response and the command doesn't execute.
With this change commands are properly executed and command output is sent to the RCON client as expected. I have used this extensively for a few weeks and I've experienced no issues.
> Allow command execution from RCON

- src/main/java/com/laytonsmith/core/functions/Cmdline.java
Sometimes, an exception would occur whenever `File#listFiles()` returned null.
The most obvious cases here were a lack of read/execute permissions and providing `ls` a file.
```
:ls('testinghi');
Uh oh! You've found an error in Core.
This happened while running your code, so you may be able to find a workaround, but is ultimately an issue in Core.
The following code caused the error:
ls('testinghi')
on or around Interpreter:1.
Please report this to the developers, and be sure to include the version numbers:
Server version: SHELL;
MethodScript version: 3.3.5;
Loaded extensions and versions:
SKCompat (3.1.2)
CHFiles (2.2.5)
MSImage (1.1.0)
Core (3.3.5)
CHSocket (1.1.0)
Here's the stacktrace:
java.lang.NullPointerException: Cannot read the array length because "<local6>" is null
at …
```
> ls: fix Core exception in certain conditions.

- src/main/java/com/laytonsmith/PureUtilities/Common/StringUtils.java
- src/main/java/com/laytonsmith/core/asm/LLVMFunction.java
- src/main/java/com/laytonsmith/core/compiler/analysis/StaticAnalysis.java
- src/main/java/com/laytonsmith/core/compiler/signature/FunctionSignature.java
- src/main/java/com/laytonsmith/core/compiler/signature/FunctionSignatures.java
- src/main/java/com/laytonsmith/core/compiler/signature/Param.java
- src/main/java/com/laytonsmith/core/compiler/signature/ReturnType.java
- src/main/java/com/laytonsmith/core/compiler/signature/SignatureBuilder.java
- src/main/java/com/laytonsmith/core/compiler/signature/Throws.java
- src/main/java/com/laytonsmith/core/constructs/InstanceofUtil.java
- src/main/java/com/laytonsmith/core/functions/AbstractFunction.java
- src/main/java/com/laytonsmith/core/functions/BasicLogic.java
- src/main/java/com/laytonsmith/core/functions/Compiler.java
- src/main/java/com/laytonsmith/core/functions/ControlFlow.java
- src/main/java/com/laytonsmith/core/functions/Function.java
- src/test/java/com/laytonsmith/core/compiler/signatures/FunctionSignaturesTest.java
This PR adds a basic function signature framework and allows for defining signatures in functions for typechecking. In the current state, any MS function signature should be creatable, but signatures with generic types are not yet handled in typechecking.
Note: As long as the [WIP] prefix is in the PR title, it should not be merged.
> Use function signatures for typechecking

- src/main/java/com/laytonsmith/PureUtilities/Common/ClassUtils.java
This fixes class name misses for inner classes, where previously this would cause an enormous number of ClassNotFoundExceptions in ClassUtils.forCanonicalName() before it re-attempts them by re-adding the '$'.
It's possible you desire to fix this in another way, but this is the smallest change that fixes it.
> Dramatically reduce extension initialization time

- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
- src/main/java/com/laytonsmith/core/functions/Compiler.java
- Make `__autoconcat__` rewrites no longer able to return `__autoconcat__` in their rewritten AST, and use this property to do only a single AST traversal for rewriting autoconcats.
- Make `__autoconcat__.rewrite(...)` static. This could eventually be moved to MethodScriptCompiler instead.
- Remove unused autoconcat construction methods.
- Simplify `p()` execs (no functional changes).
> Autoconcat optimization

- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
This avoids traversing children twice when keywords are found, and removes a redundant keyword hashmap lookup.
processKeywords easily takes the majority of compile time on my code.
> Process keywords faster

- src/main/java/com/laytonsmith/commandhelper/CommandHelperInterpreterListener.java
- src/main/java/com/laytonsmith/core/AliasCore.java
- src/main/java/com/laytonsmith/core/Script.java
- src/main/java/com/laytonsmith/core/functions/IncludeCache.java
This prevents auto_includes which write to Globals from being cleared on
second and on runs. The poorly named "registerAutoIncludes" has been
renamed to state what it actually does, which is execute them.
> Move execution of autoincludes to later.

- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
- src/main/java/com/laytonsmith/core/compiler/BothAssociativeLateBindingKeyword.java
- src/main/java/com/laytonsmith/core/compiler/EarlyBindingKeyword.java
- src/main/java/com/laytonsmith/core/compiler/FileOptions.java
- src/main/java/com/laytonsmith/core/compiler/Keyword.java
- src/main/java/com/laytonsmith/core/compiler/KeywordDocumentation.java
- src/main/java/com/laytonsmith/core/compiler/KeywordList.java
- src/main/java/com/laytonsmith/core/compiler/LateBindingKeyword.java
- src/main/java/com/laytonsmith/core/compiler/LeftAssociativeLateBindingKeyword.java
- src/main/java/com/laytonsmith/core/compiler/RightAssociativeLateBindingKeyword.java
- src/main/java/com/laytonsmith/core/compiler/keywords/ReturnKeyword.java
- src/main/java/com/laytonsmith/core/functions/ControlFlow.java
- src/main/java/com/laytonsmith/core/functions/Reflection.java
- src/main/java/com/laytonsmith/tools/docgen/sitedeploy/APIBuilder.java
- src/test/java/com/laytonsmith/core/OptimizationTest.java
There is also a start for early binding ones as well, but that is unused
for now. A LateBindingKeyword is one that is either left, right, or
both associative, but works at a very high level, where it expects one
or two parse tree nodes to surround it, and it take the whole node,
whatever that is, which may be made up of other complex items. These
binding works more or less the same as other keywords, but it runs after
autoconcats are resolved, meaning that normal binding keywords will all
have already run.
EarlyBindingKeywords are meant to operate at an extremely early stage,
operating instead of on nodes, directly on the TokenStream, so that
syntax such as commas and other extremly low level components can be
subsumed into the keyword. This is intended to be used with class
definitions …
> Add framework for late binding keywords.

- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
- Fix smart strings containing an escaped `@` not being rewritten.
- Fix `\` in 'dumb' smart strings being rewritten to `\\` in normal strings.
> Fix smart_string rewriting for dumb strings

- src/main/java/com/laytonsmith/core/functions/Compiler.java
Fixes #1323.
@LadyCailin I've requested a review from you to validate that this bug is fixed in the right spot. Problem was that for example `@a[]() @a[]() noop()` would end up in one `__autoconcat__` as a whole, while `__autoconcat__` would only rewrite to `execute()` when its contents end with a `p()` generated by the `()` in code.
> Fix execute() sugared syntax rewrite

- src/main/java/com/laytonsmith/abstraction/bukkit/entities/BukkitMCInteraction.java
- src/main/java/com/laytonsmith/abstraction/entities/MCInteraction.java
- src/main/java/com/laytonsmith/core/functions/EntityManagement.java
- src/main/resources/functionDocs/entity_spec
entity_spec for "Interaction" contains values consistent with the [entity data in Minecraft](https://minecraft.fandom.com/wiki/Interaction).
> Add "Interaction" entity to entity_spec() and set_entity_spec()

- pom.xml
Email sending did not work in our setup anymore.
And apparently updating the dependency fixes that.
Now the artifact/group is a different one.
With the difference that 'javax.mail' has not been updated since 2013, while 'com.sun.mail' was updated last in 2018 and has a higher version number.
Both seems to stem from the same original source. As the package in both are 'com.sun.mail'.
I removed the maven shade relocation for 'javax.mail'. It never did do anything, since package 'javax.mail' never existed, the dependency used 'com.sun.mail' as package. I assume it was an oversight, that this relocation was added in the first place.
There is an old relocation for 'com.sun.mail' with a comment, that it cannot be relocated due to functionality. I left that there, as that probably still applies. …
> Fix email by updating its dependency

- src/main/java/com/laytonsmith/abstraction/Convertor.java
- src/main/java/com/laytonsmith/abstraction/MCItemMeta.java
- src/main/java/com/laytonsmith/abstraction/MCNamespacedKey.java
- src/main/java/com/laytonsmith/abstraction/MCTagContainer.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitConvertor.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCItemMeta.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCNamespacedKey.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCTagContainer.java
- src/main/java/com/laytonsmith/abstraction/enums/MCTagType.java
- src/main/java/com/laytonsmith/core/ObjectGenerator.java
- src/main/java/com/laytonsmith/core/functions/ItemMeta.java
- src/main/java/com/laytonsmith/tools/Interpreter.java
- src/main/resources/functionDocs/get_itemmeta
- src/test/java/com/laytonsmith/testing/StaticTest.java
This is a proposal solution for adding custom tags from Bukkit's PersistentDataContainers in item meta. This is for preserving tags added by other plugins as well as allowing scripters more control over their own custom data stored in items. 
I'm using array objects to store NBT types along with the values. Due to API limitations we're not able to tell what type of data is under each key, so all types are checked, ordered by an estimation of frequency of use. This can be optimized later, but performance actually seemed adequate and doesn't rely on reflection.
API naming worth discussing is "type", "value", and "tags". We could also go for something like "custom" instead of "tags", "data" instead of "value"
Item array example:
```
{
"name": "IRON_PICKAXE",
"meta": {
"tags": { …
```
> Add support for custom tags in item meta

- src/main/java/com/laytonsmith/core/functions/Crypto.java
This adds a way to perform the existing crypto functions using both `byte_array` keys and values. I needed this for signing a HTTP request to access an AWS S3 bucket, which works with this modification.
Note that I also needed the following code to convert the returned hex string to a byte array:
```java
proc _hex_to_ba(string @hex) {
byte_array @ret = byte_array();
for(int @i = 0, @i < length(@hex), @i += 2) {
int @val = parse_int(substr(@hex, @i, @i + 2), 16);
ba_put_byte(@ret, if(@val < 128, @val, @val - 256));
}
return(@ret);
}
```
It could be helpful to add some `hex_string_to_ba()` function to provide this functionality out of the box, or add some option to make the hmac functions return a byte array instead of a hex string. If this is the case, issues should be created for those …
> Support passing byte_array into crypto functions

- src/main/java/com/laytonsmith/core/constructs/CClosure.java
- src/main/java/com/laytonsmith/core/environments/GlobalEnv.java
Store `StacktTraceManager` directly in `GlobalEnv` to prevent a synchronized hashmap lookup on every `eval()` and `seval()` call. Move `StackTraceManager` getter in `CClosure` to post-environment-clone to ensure that it does not overwrite the `StackTraceManager` of the original thread when called from a new thread(by for example `x_new_thread()`).
In the 5 seconds profile below, we can see that a couple of `GlobalEnv.GetStackTraceManager()` calls take up about 18% CPU time for my specific MethodScript program.
> Stacktrace manager optimization

- src/main/java/com/laytonsmith/PureUtilities/Quadruplet.java
- src/main/java/com/laytonsmith/abstraction/AbstractConvertor.java
- src/main/java/com/laytonsmith/abstraction/Convertor.java
- src/main/java/com/laytonsmith/abstraction/StaticLayer.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitConvertor.java
- src/main/java/com/laytonsmith/core/functions/ResourceManager.java
- src/main/java/com/laytonsmith/core/functions/Threading.java
- src/main/java/com/laytonsmith/core/functions/XGUI.java
- src/main/java/com/laytonsmith/tools/Interpreter.java
- src/test/java/com/laytonsmith/testing/StaticTest.java
Provide a new function, x_get_lock, which provides an asynchronous lock waiting mechanism. This uses the same underlying lock structure as synchronized(). Additionally, the lock object has now been restricted to non-value types, except strings. This is a breaking change, but is unlikely to affect anyone.
> Add x_get_lock, synchronized changes

- src/main/java/com/laytonsmith/core/functions/ArrayHandling.java
- src/main/java/com/laytonsmith/core/functions/StringHandling.java
- Export functionality of Java's `String.compareTo(String)` in MethodScript API.
- Support integer return type in array_sort closure.
This is useful to convert hacky code such as:
```java
array @arr = array(array('key': 'Hello'), array('key': 'World'), array('key': 'Aaahhh'));
@arr = array_sort(@arr, closure(@left, @right) {
return(array_sort(array(@left['key'], @right['key']), 'STRING')[0] === @right['key']);
});
```
into:
```java
array @arr = array(array('key': 'Hello'), array('key': 'World'), array('key': 'Aaahhh'));
@arr = array_sort(@arr, closure(@left, @right) {
return(string_compare(@left['key'], @right['key']));
});
```
> Add string_compare function and support integer return type in array_sort function

- src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitBlockEvents.java
- src/main/java/com/laytonsmith/abstraction/events/MCBlockPlaceEvent.java
- src/main/java/com/laytonsmith/core/events/drivers/BlockEvents.java
Adds those two keys to the event array. `item_in_hand` is a full item stack, whereas `hand` is just `main_hand`/`off_hand`.
> Add item_in_hand and hand fields to block_place event.

- src/main/java/com/laytonsmith/abstraction/MCAnvilInventory.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCAnvilInventory.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitInventoryEvents.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/drivers/BukkitInventoryListener.java
- src/main/java/com/laytonsmith/abstraction/events/MCPrepareAnvilEvent.java
- src/main/java/com/laytonsmith/core/events/Driver.java
- src/main/java/com/laytonsmith/core/events/drivers/InventoryEvents.java
Kind of flying blind with creating a new event. It's been many years since I've written one, in an extension. :joy:
Let me know if there's any validation you'd like for me to do on my end.
Example payload (pretty printed):
```
event_type: item_pre_anvil
first_item: {meta: {damage: 0, display: null, enchants: {silk_touch: {elevel: 1}, unbreaking: {elevel: 3}}, flags: {}, lore: null, model: null, modifiers: null, repair: 0, tags: null, unbreakable: false}, name: DIAMOND_PICKAXE, qty: 1}
item_repair_cost: 10
level_repair_cost: 10
macrotype: inventory
max_repair_cost: 40
result: {meta: {damage: 0, display: null, enchants: {efficiency: {elevel: 4}, silk_touch: {elevel: 1}, unbreaking: {elevel: 3}}, flags: {}, lore: null, model: null, modifiers: null, repair: 1, tags: null, unbreakable: false}, …
```
> add item_pre_anvil event

- src/main/java/com/laytonsmith/core/events/drivers/InventoryEvents.java
While writing some code around `item_pre_anvil`, I noticed you can't actually *click* the result slot if the result tool has no enchantments on it. It becomes a nothing click if the level cost isn't set.
> add modify for item_pre_anvil's item_repair_cost/level_repair_cost

- src/main/java/com/laytonsmith/abstraction/MCGrindstoneInventory.java
- src/main/java/com/laytonsmith/abstraction/MCSmithingInventory.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCGrindstoneInventory.java
- src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCSmithingInventory.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitInventoryEvents.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/drivers/BukkitInventoryListener.java
- src/main/java/com/laytonsmith/abstraction/events/MCPrepareGrindstoneEvent.java
- src/main/java/com/laytonsmith/abstraction/events/MCPrepareSmithingEvent.java
- src/main/java/com/laytonsmith/core/events/Driver.java
- src/main/java/com/laytonsmith/core/events/drivers/InventoryEvents.java
- Adding `modify_event('result', ...);` for `item_pre_craft`.
- Adding `item_pre_grindstone` (`PrepareGrindstoneEvent`) event.
- Adding `item_pre_smithing` (`PrepareSmithingEvent`) event.
> add item_pre_grindstone, item_pre_smithing; partial fix modify_event for item_pre_craft

- src/main/java/com/laytonsmith/abstraction/bukkit/events/drivers/BukkitBlockListener.java
If you call `modify_event('drops', <any item array>)` for `block_break`, there's a bit of a 'hack' in place to emulate this since [`BlockBreakEvent`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockBreakEvent.html) doesn't support rewriting drops natively.
Since we offset the location then do a `dropItemNaturally` call, it can sometimes send the item *into* another block, which causes it to shoot to the surface if they're underground. Not ideal.
I've attached links to two gifs. They're a bit large (and might play slow until they download fully). Hopefully it visualizes what happens.
Before: (~13MB) https://dirt.wtf/1ebnnKc8Pne20dm0.gif
After: (~8MB) https://dirt.wtf/VFB66bDgc6zGsRFa.gif
> Fix location shift in block_break so dropped items aren't placed into adjacent blocks.

- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
- src/main/java/com/laytonsmith/core/Static.java
- src/test/java/com/laytonsmith/core/MethodScriptCompilerTest.java
- src/test/java/com/laytonsmith/core/TestStatic.java
- Support max 64-bit hex/oct/bin value literals, rather than only up to 63 bits.
- Fix uncaught exceptions when supplying hex/oct/bin literals that do not fit 63 bits (64 bits with the above mentioned change).
- Add tests for these number formats.
> Support max hex/oct/bin literals + Fix uncaught exceptions when providing too large hex/oct/bin literals

- src/main/java/com/laytonsmith/core/MethodScriptCompiler.java
- src/main/java/com/laytonsmith/core/functions/Compiler.java
Checks binary operators for unexpected adjacent symbols during auto concat rewrite.
Does adjacent symbol token detection in aliases too. This was limited to when inPureMScript, skipping the right side of aliases.
> Improve early detection of errant symbols

- .gitignore
- .vscode/extensions.json
- .vscode/java-formatter.xml
- .vscode/settings.json
- src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitEntityEvents.java
- src/main/java/com/laytonsmith/abstraction/bukkit/events/drivers/BukkitEntityListener.java
- src/main/java/com/laytonsmith/abstraction/events/MCEntityEvent.java
- src/main/java/com/laytonsmith/abstraction/events/MCEntityToggleSwimEvent.java
- src/main/java/com/laytonsmith/core/events/Driver.java
- src/main/java/com/laytonsmith/core/events/drivers/EntityEvents.java
- src/main/java/com/laytonsmith/core/events/prefilters/OptionalPlayerPrefilterMatcher.java
I added presets for vscode, specifically the code formatting configuration. Tried to make it the best fit for the project, but there are inconsistencies in it project itself, and some of the rules just can't be turned off. Anyway this is only for vscode and only if you execute formating manually.
> Add vscode presetting and entity toggle swim event
