src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCTameable.java
src/main/java/com/laytonsmith/core/functions/Minecraft.java

also fixed exception if calling from a non player context
Fixes CMDHELPER-2962

Fixed exception on null owner in tame_mob(owner,entity)

---

src/main/java/com/laytonsmith/abstraction/blocks/MCBlock.java
src/main/java/com/laytonsmith/abstraction/bukkit/blocks/BukkitMCBlock.java
src/main/java/com/laytonsmith/core/functions/World.java

Fetch the current temperature of the location given.

Added get_temperature()

---

src/main/java/com/laytonsmith/abstraction/MCServer.java
src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCServer.java
src/main/java/com/laytonsmith/core/functions/Minecraft.java

Added server IP to get_server_info(12) which gives the current server IP

Added server IP to get_server_info(12) which gives the current server IP

---

src/main/java/com/laytonsmith/core/events/drivers/PlayerEvents.java
src/main/java/com/laytonsmith/core/events/drivers/ServerEvents.java
src/main/java/com/laytonsmith/core/functions/Minecraft.java
src/main/java/com/laytonsmith/core/functions/PlayerManagement.java
src/main/java/com/laytonsmith/core/functions/World.java
src/main/resources/docs/Advanced Guide

This fixes four reported issues in the documentation, as well as three others I noticed.

Updated some documentation

---

src/main/resources/syntax-templates/notepad++/default.xml
src/main/resources/syntax-templates/notepad++/obsidian.xml
src/main/resources/syntax-templates/notepad++/solarized_dark.xml
src/main/resources/syntax-templates/notepad++/solarized_light.xml

Added semicolons to np++ syntax templates.

---

src/main/java/com/laytonsmith/core/functions/World.java

- get_pitch() returned pfacing()[1] * -1 instead of pfacing()[1].
- get_yaw() returned a double in the range of [-90, 270] instead of [0,360]. The values correspond to pfacing()[0] now.

Changed get_pitch() and get_yaw() functions to correspond to the pfacing() values + docsfix.

---

src/main/java/com/laytonsmith/commandhelper/CommandHelperPlugin.java

Make dynamic event registering work when the event shares a handler list with its superclass.

Fix for NoSuchMethodException in dynamic events.

---

src/main/java/com/laytonsmith/core/functions/DataTransformations.java

Fixed unhandled exception in yml_decode.

---

src/main/java/com/laytonsmith/tools/SyntaxHighlighters.java
src/main/resources/syntax-templates/atom/default.cson

Adds Atom syntax highlighting support - used to build https://atom.io/packages/language-mscript
:+1:

Add atom syntax highlighting

---

src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitWeatherEvents.java
src/main/java/com/laytonsmith/abstraction/bukkit/events/drivers/BukkitWeatherListener.java
src/main/java/com/laytonsmith/abstraction/events/MCLightningStrikeEvent.java
src/main/java/com/laytonsmith/abstraction/events/MCThunderChangeEvent.java
src/main/java/com/laytonsmith/abstraction/events/MCWeatherChangeEvent.java
src/main/java/com/laytonsmith/abstraction/events/MCWeatherEvent.java
src/main/java/com/laytonsmith/core/events/Driver.java
src/main/java/com/laytonsmith/core/events/drivers/WeatherEvents.java

These have been tested locally and work.  Documentation has been added.
:tada:

Expose lightning_strike, thunder_change, and weather_change events

---

src/main/java/com/laytonsmith/core/functions/PlayerManagement.java

It will now re-set them back in the vehicles they belong in.

Bugfix - pfacing() caused players to exit their vehicles.

---

src/main/java/com/laytonsmith/PureUtilities/Common/ReflectionUtils.java

I believe this is correct. It tested perfectly on my server.

Fix ReflectionUtils.getMethod() incorrectly returning false; Fixes CMDHELPER-3060

---

src/main/java/com/laytonsmith/PureUtilities/Point3D.java
src/main/java/com/laytonsmith/PureUtilities/Vector3D.java
src/main/java/com/laytonsmith/core/functions/EntityManagement.java

- Removed (the only) use of the deprecated Vector3D and Point3D and their constructors.
- Added javadoc to Vector3D.ZERO.
- Redirected all constructors to class..(x, y, z).

Removed deprecated constructors + minor changes.

---

src/main/java/com/laytonsmith/abstraction/bukkit/entities/BukkitMCPlayer.java

I also tested this to be sure it works.

Update Temp Op for 1.8.6

---

pom.xml
src/main/java/com/laytonsmith/PureUtilities/Common/ReflectionUtils.java
src/main/java/com/laytonsmith/abstraction/MCTeam.java
src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCObjective.java
src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCScoreboard.java
src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCTeam.java
src/main/java/com/laytonsmith/core/functions/Scoreboards.java

Tested on 1.7.2 and 1.8.3 just to make sure it's all working this time.

Fixes CMDHELPER-3060

---

src/main/java/com/laytonsmith/abstraction/MCItemMeta.java
src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCItemMeta.java
src/main/java/com/laytonsmith/abstraction/enums/MCItemFlag.java
src/main/java/com/laytonsmith/abstraction/enums/bukkit/BukkitMCItemFlag.java
src/main/java/com/laytonsmith/core/ObjectGenerator.java
src/main/java/com/laytonsmith/core/functions/ItemMeta.java

set_itemmeta() and get_itemmeta() now accept array('itemflags':
array('FLAG1', 'FLAG2', 'etc')) with all ItemFlag values currently
supported by bukkit.

Added ItemFlag support to set/get_itemmeta.

---

src/main/java/com/laytonsmith/core/functions/PlayerManagement.java

Fix for common scripts that use a player entity id in entity functions

Return UUID for pinfo(13)

---

pom.xml
src/main/java/com/laytonsmith/PureUtilities/ClassLoading/ClassMirror/ClassMirror.java

Supports Minecraft Servers that use Java 8
Needed for [TacoSpigot](https://github.com/TacoSpigot/TacoSpigot)

Update to ASM 5.0

---

src/main/java/com/laytonsmith/core/functions/InventoryManagement.java

void pset_selected_quickbar_slot([player], slot)
The function selects the specified quickbar slot.

Added set_pheld_slot and pheld_slot function.

---

src/main/java/com/laytonsmith/PureUtilities/ExecutionQueue.java
src/main/java/com/laytonsmith/abstraction/enums/MCBiomeType.java
src/main/java/com/laytonsmith/abstraction/enums/MCEntityType.java
src/main/java/com/laytonsmith/core/ObjectGenerator.java
src/main/java/com/laytonsmith/core/Static.java
src/main/java/com/laytonsmith/core/functions/Cmdline.java
src/main/java/com/laytonsmith/core/functions/Commands.java
src/main/java/com/laytonsmith/core/functions/Compiler.java
src/main/java/com/laytonsmith/core/functions/Enchantments.java
src/main/java/com/laytonsmith/core/functions/EntityManagement.java
src/main/java/com/laytonsmith/core/functions/Environment.java
src/main/java/com/laytonsmith/core/functions/FileHandling.java
src/main/java/com/laytonsmith/core/functions/InventoryManagement.java
src/main/java/com/laytonsmith/core/functions/ItemMeta.java
src/main/java/com/laytonsmith/core/functions/Minecraft.java
src/main/java/com/laytonsmith/core/functions/Permissions.java
src/main/java/com/laytonsmith/core/functions/PlayerManagement.java
src/main/java/com/laytonsmith/core/functions/PluginMeta.java
src/main/java/com/laytonsmith/core/functions/Sandbox.java
src/main/java/com/laytonsmith/core/functions/Scoreboards.java
src/main/java/com/laytonsmith/core/functions/World.java
src/test/java/com/laytonsmith/testing/ProcedureTest.java
src/test/java/com/laytonsmith/testing/StaticTest.java

The days of building CH without the test case error spam are finally
here.

Fixed 200+ errors in core under extreme conditions (Yay $20).

---

src/main/java/com/laytonsmith/core/functions/Commands.java

Who doesn't like hugs? The example shows how to use all indices of the
options array.

Added "/hug" example to register_command.

---

src/main/java/com/laytonsmith/core/functions/Commands.java

Display the player offline message when the player is offline instead of
online.

Fix in register_command example.

---

src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitPlayerEvents.java
src/main/java/com/laytonsmith/abstraction/events/MCPlayerLoginEvent.java
src/main/java/com/laytonsmith/core/events/drivers/PlayerEvents.java

Added "hostname" to event data for player_login event.

---

src/main/java/com/laytonsmith/core/Globals.java
src/main/java/com/laytonsmith/core/functions/DataHandling.java
src/main/java/com/laytonsmith/core/functions/DataTransformations.java
src/test/java/com/laytonsmith/core/functions/DataHandlingTest.java

These are the changes mentioned here:
http://dev.enginehub.org/youtrack/issue/CMDHELPER-2847

Replace deprecated import/export format with array keys and default values

---

src/main/java/com/laytonsmith/core/functions/ArrayHandling.java
src/test/java/com/laytonsmith/core/functions/ArrayHandlingTest.java

Works like array_contains, but returns false if the types don't match.

Added array_scontains.

---

src/test/java/com/laytonsmith/core/functions/ArrayHandlingTest.java

Apparentally, no one likes the Windows GitHub client for a reason.

Fixed unit test.

---

src/main/java/com/laytonsmith/PureUtilities/Web/WebUtility.java

Fix again. It's surely working.

http_request charset fix again

---

src/main/java/com/laytonsmith/core/events/drivers/ServerEvents.java

When modifying the player list in server_ping, a PlayerOfflineException
would be thrown if a player leaves between the time the player list for
the event was created and when the event was modified by modify_event()
in CommandHelper. Instead of checking which player should be on the
list, it now checks which players should NOT be on the list, fixing this
issue. Another noticable change is that players on the list that were
not online when the event was created will simply be ignored, where
previously a PlayerOfflineException was thrown.

Fixed PlayerOfflineEx in server_ping.

---

src/main/java/com/laytonsmith/core/functions/Minecraft.java

- Added the max qty to the docs.
- Added the max qty in the RangeException that is thrown when the max
qty is exceeded.

Added info about range in RangeException in spawn_mob.

---

src/main/java/com/laytonsmith/abstraction/MCEntity.java
src/main/java/com/laytonsmith/abstraction/MCLivingEntity.java
src/main/java/com/laytonsmith/abstraction/bukkit/entities/BukkitMCEntity.java
src/main/java/com/laytonsmith/abstraction/bukkit/entities/BukkitMCLivingEntity.java
src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitEntityEvents.java
src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitPlayerEvents.java
src/main/java/com/laytonsmith/abstraction/bukkit/events/drivers/BukkitEntityListener.java
src/main/java/com/laytonsmith/abstraction/events/MCEntityToggleGlideEvent.java
src/main/java/com/laytonsmith/abstraction/events/MCPlayerInteractEvent.java
src/main/java/com/laytonsmith/core/events/Driver.java
src/main/java/com/laytonsmith/core/events/drivers/EntityEvents.java
src/main/java/com/laytonsmith/core/events/drivers/PlayerEvents.java
src/main/java/com/laytonsmith/core/functions/EntityManagement.java

* Added event entity_toggle_glide
* Added functions for setting gliding and glowing states of entities
* Added support for hand types to player_interact

1.9 related additions, squashes #403

---

src/main/java/com/laytonsmith/core/functions/Math.java

Using mod(@var, 0) would throw a ArithmeticException ("Division by 0").
This commit fixes that.

Fixed an NPE in mod(@var, 0).

---

src/main/java/com/laytonsmith/abstraction/bukkit/BukkitConvertor.java
src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitInventoryEvents.java
src/main/java/com/laytonsmith/abstraction/bukkit/events/drivers/BukkitInventoryListener.java
src/main/java/com/laytonsmith/commandhelper/CommandHelperPlugin.java
src/main/java/com/laytonsmith/core/events/Driver.java

Also change registerEventsDynamic to be able to handle listeners with only the standard Bukkit annotation.

Register item_swap and entity_toggle_glide dynamically.

---

src/main/java/com/laytonsmith/core/events/drivers/PlayerEvents.java

There was a wrong check for null.

Patch for player_interact event compatibility.

---

src/main/java/com/laytonsmith/core/functions/Cmdline.java

It'd be nice to have a function that tells you whether you are in
CMDline mode or not. This does that.

Added in_cmdline_mode.

---

src/main/java/com/laytonsmith/core/functions/StringHandling.java
src/test/java/com/laytonsmith/core/functions/StringHandlingTest.java

Only took the lifetime of a small insect.

Added char_is_uppercase.

---

pom.xml
src/main/java/com/laytonsmith/abstraction/bukkit/entities/BukkitMCSnowman.java
src/main/java/com/laytonsmith/abstraction/entities/MCSnowman.java
src/main/java/com/laytonsmith/core/functions/EntityManagement.java
src/main/resources/functionDocs/entity_spec

"derp mode" is true if the snowman does't have a pumpkin on it's head

Added support for snowman "derp mode" in the entity spec functions

---

src/main/java/com/laytonsmith/core/compiler/keywords/SynchronizedKeyword.java
src/main/java/com/laytonsmith/core/functions/Threading.java

This function synchronizes the code ran in the closure with any other
thread that has called the synchronize(name, closure) function using the
same name String (by value). For more info, read _synchronized.docs().

Added synchronize function.

---

src/main/resources/syntax-templates/notepad++/default.xml
src/main/resources/syntax-templates/notepad++/obsidian.xml
src/main/resources/syntax-templates/notepad++/solarized_dark.xml
src/main/resources/syntax-templates/notepad++/solarized_light.xml

Detect "//" as a line comment indicator.

Npp syntax template fix

---

src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitInventoryEvents.java
src/main/java/com/laytonsmith/abstraction/events/MCInventoryClickEvent.java
src/main/java/com/laytonsmith/core/events/drivers/InventoryEvents.java

When clicking the specific item, i tried to cancel the inventory_click event.
But if swap the hotbar, I can't check the items.

Add HotbarButton info in inventory_click event

---

src/main/java/com/laytonsmith/abstraction/MCWorld.java
src/main/java/com/laytonsmith/abstraction/MCWorldBorder.java
src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCWorld.java
src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCWorldBorder.java
src/main/java/com/laytonsmith/core/functions/World.java

Chose "width" instead of "size", as it's more clear.

Add get|set_world_border

---

src/main/java/com/laytonsmith/abstraction/MCPlayer.java
src/main/java/com/laytonsmith/abstraction/bukkit/entities/BukkitMCPlayer.java
src/main/java/com/laytonsmith/core/functions/Echoes.java

Last chance to comment on the name, parameters and documentation.
Other proposed names included send_title(), psend_title(), show_title(), and title_msg(). These were for the most part not any more descriptive, so I decided to keep it simple, just like most other echo functions.

Add title()

---

src/main/java/com/laytonsmith/tools/SyntaxHighlighters.java
src/main/resources/syntax-templates/sublime3/default.sublime-syntax

I am using a Subl3 Highlighting for a while, which I refactored from the old sublime syntax file.

Sublime Text 3 - Syntax Highlighting

---

src/main/java/com/laytonsmith/core/events/drivers/BlockEvents.java
src/main/java/com/laytonsmith/core/events/drivers/EntityEvents.java
src/main/java/com/laytonsmith/core/events/drivers/InventoryEvents.java
src/main/java/com/laytonsmith/core/events/drivers/PlayerEvents.java
src/main/java/com/laytonsmith/core/events/drivers/PluginEvents.java
src/main/java/com/laytonsmith/core/events/drivers/ServerEvents.java
src/main/java/com/laytonsmith/core/events/drivers/VehicleEvents.java
src/main/java/com/laytonsmith/core/events/drivers/WeatherEvents.java
src/main/java/com/laytonsmith/core/functions/MobManagement.java
src/main/java/com/laytonsmith/tools/docgen/sitedeploy/SiteDeploy.java
src/main/resources/siteDeploy/LearningTrail.json
src/main/resources/siteDeploy/index.js
src/main/resources/siteDeploy/resources/css/styles.css

You might have something to say about a couple these changes, but I think it'd be good to pull now and deploy, then make your adjustments later. Still, I wanted to PR this just in case you were working on this.
- Adds Event API
- Fixes incorrect instanceof variable check when generating the learning trail
- Fixes deployment on Windows for local testing
- Removes splitting columns on || which breaks on OR operators, and as far as I can tell is never used
- Tweaks readability/compactness with modest adjustments to the stylesheet and columns
- Removed extension-specific entries on the learning trail and moved some things around based on priority

Add Events and other fixes to site deployment

---

src/main/java/com/laytonsmith/core/compiler/Keyword.java

Replaced an exception throw + catch with equivalent logic. On my server
with my setup, this removes ~6.5% of the total script recompile time.

Keyword compile optimization.

---

pom.xml
src/main/java/com/laytonsmith/core/functions/StringHandling.java
src/test/java/com/laytonsmith/core/functions/StringHandlingTest.java

Added optimizations and examples to string_starts/ends_with and char_is_uppercase.

---

src/main/java/com/laytonsmith/core/MethodScriptCompiler.java

Change the code target to the last opening '({[' that does not have a closing ')}]', instead of always returning the last line of the script for such CRE's.

Improve code target for mismatched parens

---

src/main/java/com/laytonsmith/core/events/drivers/PlayerEvents.java

When binding multiple player_move events with the same threshold and then unbinding one of those events, all events would not trigger anymore until another event with the same treshold would be bound. This bug is caused by the unbind code removing a threshold without checking whether more events still use it.

BugFix: Fix unbinding player_move to unbind multiple player_move events

---

src/main/java/com/laytonsmith/core/functions/Minecraft.java
src/main/java/com/laytonsmith/core/functions/World.java

- Allow flight disables (not enables) the anti-flight.
- Add missing maxHeight key.

Fix get_server_info and world_info documentation

---

src/main/java/com/laytonsmith/core/functions/DataHandling.java

The optional 'key' argument was missing.

Fix foreachelse documentation

---

src/main/java/com/laytonsmith/abstraction/MCEnchantmentOffer.java
src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCEnchantmentOffer.java
src/main/java/com/laytonsmith/abstraction/bukkit/events/BukkitInventoryEvents.java
src/main/java/com/laytonsmith/abstraction/events/MCPrepareItemEnchantEvent.java
src/main/java/com/laytonsmith/core/events/drivers/InventoryEvents.java

getExpLevelCostsOffered() was deprecated and we can't modify the cost using this

Fix api usage of offers in item_pre_enchant

---

src/main/java/com/laytonsmith/abstraction/Convertor.java
src/main/java/com/laytonsmith/abstraction/StaticLayer.java
src/main/java/com/laytonsmith/abstraction/blocks/MCMaterial.java
src/main/java/com/laytonsmith/abstraction/bukkit/BukkitConvertor.java
src/main/java/com/laytonsmith/abstraction/bukkit/blocks/BukkitMCMaterial.java
src/main/java/com/laytonsmith/core/functions/Minecraft.java
src/main/java/com/laytonsmith/tools/Interpreter.java
src/test/java/com/laytonsmith/testing/StaticTest.java

I really worried about where `getMaterialValues()` should be placed.
I refered `getEnchantmentValues` so I placed it in BukkitConverter.

Add all_materials() function

---

src/main/java/com/laytonsmith/abstraction/blocks/MCSkull.java
src/main/java/com/laytonsmith/abstraction/bukkit/BukkitConvertor.java
src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCOfflinePlayer.java
src/main/java/com/laytonsmith/abstraction/bukkit/blocks/BukkitMCBlock.java
src/main/java/com/laytonsmith/abstraction/bukkit/blocks/BukkitMCSkull.java
src/main/java/com/laytonsmith/core/functions/Environment.java

These functions can be used to get/set/clear the skull owner on player heads.

Add get/set_skull_owner functions

---

src/main/java/com/laytonsmith/commandhelper/CommandHelperInterpreterListener.java

- Fix in-game interpreter mode from disabling when the executed code results in a compile error.
- Prevent players from being set to interpreter mode through the CommandHelperInterpreterListener.execute() method.

Fix interpreter mode stopping on compile error

---

src/test/java/com/laytonsmith/core/MethodScriptCompilerTest.java
src/test/java/com/laytonsmith/core/functions/DataHandlingTest.java
src/test/java/com/laytonsmith/core/functions/MetaTest.java

Correction of some tests so that there are no errors in the logs from static analysis, for which tests are not designed, i hope.

Clean log tests

---

src/main/java/com/laytonsmith/core/events/drivers/WorldEvents.java

Update tree_grow event documentation

---

src/main/java/com/laytonsmith/core/functions/Threading.java

Make threads remove themselves from the active threads map when they finish execution, rather than when the construct containing the thread ID string gets garbage collected.

Persist running `x_new_thread` threads over recompiles

---

src/main/java/com/laytonsmith/abstraction/MCHumanEntity.java
src/main/java/com/laytonsmith/abstraction/bukkit/entities/BukkitMCHumanEntity.java
src/main/java/com/laytonsmith/core/functions/PlayerManagement.java

Passthrough function for `HumanEntity#getAttackCooldown()`. Tested on 1.16+ only.

Added pattack_cooldown().

---

src/main/java/com/laytonsmith/core/functions/Exceptions.java

Fix several raw compile exceptions caused by invalid try/catch MethodScript syntax. Note that the checks performed in this optimization method should eventually be split into postParseRewrite or the try keyword parsing and typechecking.
Fixes #1253.

Fix several complex_try raw compile exceptions

---

src/main/resources/syntax-templates/sublime3/default.sublime-syntax

@Pieter12345 hinted me, that I still had an outdated keyword list in the syntax file. Improved that as well.

Improve Sublime3 Syntax-Highlighting

---

src/main/resources/siteDeploy/resources/css/themes/nilleke_dark.css

CSS - Nilleke Dark - Undo logo/header changes

---

src/main/java/com/laytonsmith/core/functions/ArrayHandling.java
src/main/java/com/laytonsmith/core/functions/InventoryManagement.java
src/main/java/com/laytonsmith/core/functions/PlayerManagement.java

Fixed the issue with `array_index_exists` example 6.
Added usage examples for other functions.

Documentation fixes and improvements

---

src/main/java/com/laytonsmith/abstraction/MCWorld.java
src/main/java/com/laytonsmith/abstraction/bukkit/BukkitMCWorld.java
src/main/java/com/laytonsmith/core/functions/World.java

Back at it again with my bi-yearly two-function PR.
Adding get_world_autosave and set_world_autosave as I may have an automation need for it.
Looks like Pieter requested this in #1288 too.

Add get_world_autosave, set_world_autosave.

---

src/main/java/com/laytonsmith/core/functions/Cmdline.java

tested using 3 args, seems to work fine.

Let x_find accept 3 arguments, as intended.

---

src/main/java/com/laytonsmith/core/Main.java
src/main/java/com/laytonsmith/core/Static.java
src/main/java/com/laytonsmith/core/compiler/keywords/ClassKeyword.java
src/main/java/com/laytonsmith/tools/Interpreter.java

Some trivial fixes. Most just contemplate abrupt terminations on the interpreter.

Minor fixes

---

src/main/resources/docs/Events

The link caused a 404 while it should have gone to the Event API page

Fix Event API Link

---

src/main/java/com/laytonsmith/core/compiler/keywords/SwitchKeyword.java

Replace index-based `LinkedList` access with iterator access where feasible to improve compiler runtime performance.

Switch keyword optimization
